# Integración y normalización de datos de ventas

In [27]:
#Aca importo todas las librerias que necesito

import pandas as pd
import os

In [28]:
#Creo el Data Frame de Ventas

ventas = pd.DataFrame({
    "id_producto": [101, 102, 103, 101],
    "cantidad": [2, 1, 5, 3],
    "fecha": ["2026-09-01", "2026-09-01", "2026-09-02", "2026-09-03"]
})

#Aca guardo el DF en CSV

ventas.to_csv("ventas.csv", index=False)

ventas

   id_producto  cantidad       fecha
0          101         2  2026-09-01
1          102         1  2026-09-01
2          103         5  2026-09-02
3          101         3  2026-09-03

In [29]:
#Creamos el Data frame de Productos

productos = pd.DataFrame({
    "id_producto": [101, 102, 103],
    "nombre_producto": ["Teclado", "Mouse", "Monitor"],
    "precio_unitario": [5000,1500,180000]
})

#Aca guardo el df en formato Excel

productos.to_excel("productos.xlsx", index=False)

productos

   id_producto nombre_producto  precio_unitario
0          101         Teclado             5000
1          102           Mouse             1500
2          103         Monitor           180000

In [30]:
#Aca uno las dos tablas mediante el indice ID_Producto con el MERGE

ventas_completas = pd.merge(
    ventas,
    productos,
    on="id_producto",
    how="left"
)

ventas_completas

   id_producto  cantidad       fecha nombre_producto  precio_unitario
0          101         2  2026-09-01         Teclado             5000
1          102         1  2026-09-01           Mouse             1500
2          103         5  2026-09-02         Monitor           180000
3          101         3  2026-09-03         Teclado             5000

In [36]:
ventas_completas["total_venta"] = ventas_completas["cantidad"] * ventas_completas["precio_unitario"]

ventas_completas

,id_producto,cantidad,fecha,nombre_producto,precio_unitario,total_venta
0,101,2,2026-09-01,Teclado,5000,10000
1,102,1,2026-09-01,Mouse,1500,1500
2,103,5,2026-09-02,Monitor,180000,900000
3,101,3,2026-09-03,Teclado,5000,15000

In [37]:
#Convierto la fecha como DateTime ya que pandas lo interpretaba como Texto

ventas_completas["fecha"] = pd.to_datetime(
    ventas_completas["fecha"]
)

ventas_completas.dtypes

id_producto                 int64
cantidad                    int64
fecha              datetime64[ns]
nombre_producto            object
precio_unitario             int64
total_venta                 int64
dtype: object

In [39]:
#verifico la existencia de Nulos

ventas_completas.isnull().sum()

id_producto        0
cantidad           0
fecha              0
nombre_producto    0
precio_unitario    0
total_venta        0
dtype: int64

In [38]:
#convierto Ventas Completas en archivo Parquet

ventas_completas.to_parquet(
    "ventas_final.parquet",
    index=False
)

In [32]:
#Importo la libreria OS arriba y ejecuto listdir para ver como esta cada archivo guardado.

os.listdir()

['.config',
 'productos.xlsx',
 'ventas.csv',
 'ventas_final.parquet',
 'sample_data']

In [33]:
#Aca leo el archivo Parquet

df_final = pd.read_parquet("ventas_final.parquet")

df_final

,id_producto,cantidad,fecha,nombre_producto,precio_producto,total_venta
0,101,2,2026-09-01,Teclado,5000,10000
1,102,1,2026-09-01,Mouse,1500,1500
2,103,5,2026-09-02,Monitor,180000,900000
3,101,3,2026-09-03,Teclado,5000,15000

In [40]:
#Imprimimos cada resultado para una muestra Final

print("Filas:", len(df_final))
print("Columnas:", list(df_final.columns))
print("Valores nulos:")
print(df_final.isnull().sum())
print("\nTipos de datos:")
print(df_final.dtypes)

Filas: 4
Columnas: ['id_producto', 'cantidad', 'fecha', 'nombre_producto', 'precio_producto', 'total_venta']
Valores nulos:
id_producto        0
cantidad           0
fecha              0
nombre_producto    0
precio_producto    0
total_venta        0
dtype: int64

Tipos de datos:
id_producto                 int64
cantidad                    int64
fecha              datetime64[ns]
nombre_producto            object
precio_producto             int64
total_venta                 int64
dtype: object

In [41]:
print("pandas:", pd.__version__)

pandas: 2.2.3